spring.application.name=SpringS
spring.profiles.active=postgres
api.key = bizim api

server.port=8080


#github
#spring.security.oauth2.client.registration.github.client-id=Ov23liqOCHAL8g4CbLu3
#spring.security.oauth2.client.registration.github.client-secret=c2b9720196f6b6601e81d1a5e7e5bea7335b1d6a
#spring.security.oauth2.client.registration.github.scope=read:user,user:email
#spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
#
#spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
#spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
#spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
#spring.security.oauth2.client.provider.github.user-name-attribute=login



#google
#spring.security.oauth2.client.registration.google.client-id=1048098885606-kve7nt1j4teff4h3edoq2s6n7u7oj9kv.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
#
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub

#Facebook
spring.security.oauth2.client.registration.facebook.client-id=1090548796240196
spring.security.oauth2.client.registration.facebook.client-secret=552b6143d9f19df143092ef7374ffaab
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v11.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v11.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email
spring.security.oauth2.client.provider.facebook.user-name-attribute=id

